<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.17">
  <POU Name="MAIN" Id="{8387df1b-6459-4265-8430-c8efd58f406a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	hello:BOOL;
	newVar:INT;
	newone:INT;
	nextone:REAL;
	thisisnotInGits_1:REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>
